### PR TITLE
feat(styles): notification in dialog

### PR DESCRIPTION
**Pull request by platon-rov**
## Related Issue

Refers to https://github.com/SAP/fundamental-ngx/pull/8525

## Description

Notifications in dialog update.

### After:

image

### CODE REVIEW

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Screen Shot 2022-08-18 at 1 00 56 PM
- There's no way to dismiss the dialog
- on mobile the dialog should take the whole screen. Here are the guidelines: https://experience.sap.com/internal/fiori-design-web/dialog/#size-s-smartphone


Also check the UX guidelines: https://experience.sap.com/internal/fiori-design-web/notification-center/

**Comment by platon-rov** [comment]
> * There's no way to dismiss the dialog

Fixed.

> * On mobile the dialog should take the whole screen. 
> Here are the guidelines: https://experience.sap.com/internal/fiori-design-web/dialog/#size-s-smartphone
> Also check the UX guidelines: https://experience.sap.com/internal/fiori-design-web/notification-center/

There is nothing about the mobile dialog, it's just about the notifications in the dialog. If needed, the dialog may be additionally configured.

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Screen Shot 2022-08-19 at 10 13 27 AM
Screen Shot 2022-08-19 at 10 13 21 AM

You should probably use the compact button and align it with the other dismiss buttons (that belong to the notifications) as this will be immediately reported as a bug by the designers.

**Comment by InnaAtanasova** [comment]
> > * There's no way to dismiss the dialog
> 
> Fixed.
> 
> > * On mobile the dialog should take the whole screen.
> >   Here are the guidelines: https://experience.sap.com/internal/fiori-design-web/dialog/#size-s-smartphone
> >   Also check the UX guidelines: https://experience.sap.com/internal/fiori-design-web/notification-center/
> 
> There is nothing about the mobile dialog, it's just about the notifications in the dialog. If needed, the dialog may be additionally configured.

I provided these links as it specifies that the actions are in the footer:
"On smartphones, a dialog can have one or two actions, which are located in the footer and right-aligned." 
This would mean that dismissing the notification dialog should be done by a `Cancel` button in the footer, not in the header (**in my opinion**)
Screen Shot 2022-08-19 at 10 17 59 AM

**Comment by platon-rov** [comment]
> You should probably use the compact button and align it with the other dismiss buttons (that belong to the notifications) as this will be immediately reported as a bug by the designers.

Not a bug actually. Dialog has 1rem padding on the sides and notification has 0.5rem on the right side.

> I provided these links as it specifies that the actions are in the footer:

Fixed.

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
Dialog is too wide for the notifications:

Screen Shot 2022-08-23 at 9 58 44 AM

**Review by mikerodonnell89 — APPROVED** [review]
looks good! I do agree with Inna that the margins look strange but if that's the design, it is out of our hands. Definitely looks a little better with the cancel button in the footer rather than the X bottom in the header.

**Comment by InnaAtanasova** [comment]
Screen Shot 2022-09-07 at 3 36 31 PM

Should it look like this in mobile?

**Comment by platon-rov** [comment]
> Should it look like this in mobile?

Nothing about notification itself, it comes from the dialog.

**Comment by InnaAtanasova** [comment]
> > Should it look like this in mobile?
> 
> Nothing about notification itself, it comes from the dialog.

it doesn't matter :) We shouldn't merge something that is broken or doesn't look ok. If it's coming from the dialog, either open a new issue that should be fixed asap and link it here, or fix it in a separate PR and link it here. But we can't merge this PR and just ignore the fact that in mobile the notifications look broken. @droshev what is your opinion?

**Comment by platon-rov** [comment]
> it doesn't matter :) We shouldn't merge something that is broken or doesn't look ok. If it's coming from the dialog, either open a new issue that should be fixed asap and link it here, or fix it in a separate PR and link it here. But we can't merge this PR and just ignore the fact that in mobile the notifications look broken. @droshev what is your opinion?

Opened a pr that fixes this issue

https://github.com/SAP/fundamental-styles/pull/3882

image

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
