### PR TITLE
docs: bring different image into examples

### PR DESCRIPTION
**Pull request by JKMarkowski**
## Related Issue
part of https://github.com/SAP/fundamental-styles/issues/1760

### CODE REVIEW

**Comment by prsdthkr** [comment]
Instead of depending on these image services, would it make sense to just pull some images from https://www.sapbrandtools.com/ and save locally in storybook static? We don't have to hop from one service to another that way. Also, image snapshots will give consistent results.

**Comment by InnaAtanasova** [comment]
> https://www.sapbrandtools.com/

I completely agree with you!

**Comment by InnaAtanasova** [comment]
> Instead of depending on these image services, would it make sense to just pull some images from https://www.sapbrandtools.com/ and save locally in storybook static? We don't have to hop from one service to another that way. Also, image snapshots will give consistent results.

I 100%  share @prsdthkr  opinion on this.

**Comment by JKMarkowski** [comment]
Hello @prsdthkr, that's great idea, I added some SAP image as a asset

**Review by InnaAtanasova — APPROVED** [review]

**Review by salarenko — APPROVED** [review]

**Comment by JKMarkowski** [comment]
Thanks @prsdthkr for awesome work there :)

**Pull request merged**
