### PR TITLE
fix: reworked styles for button and related components

### PR DESCRIPTION
**Pull request by mykolavorobiov**
## Related Issue
https://github.com/SAP/fundamental-ngx/issues/3458

## Description
Fix for input group component focus state. Required for https://github.com/SAP/fundamental-ngx/pull/4204
Small rework for button component and related components (combobox, carousel, input group, tile)

### Before:
image

### After:
image

#### Please check whether the PR fulfills the following requirements
1. The output matches the design specs
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] Verified all styles in IE11
4. Documentation
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Comment by mykolavorobiov** [comment]
@stefanoScalzo 
I saw fix related to combobox only in your PR https://github.com/SAP/fundamental-styles/pull/1973. But this issue related to input group and button in general. Please check.

**Comment by stefanoScalzo** [comment]
> @stefanoScalzo
> I saw fix related to combobox only in your PR #1973. But this issue related to input group and button in general. Please check.

Well it should be for all elements that use select

**Comment by mykolavorobiov** [comment]
@stefanoScalzo 
> Well it should be for all elements that use select
oh, `select` and `combobox` 're different components.
But `select` looks like `combobox`.
Anyway, I fixed button component and input group.

**Comment by JKMarkowski** [comment]
IMO It should be applied to input group, because almost every pattern uses it.
The problem is that IE11 doesn't support `outline-offset`:
image
So I'm not sure if it can be approved.
@InnaAtanasova @mikerodonnell89

**Comment by stefanoScalzo** [comment]
> IMO It should be applied to input group, because almost every pattern uses it (I would add `&::focus-within` selector, but it's not supported by IE11).
> The problem is that IE11 doesn't support `outline-offset`:
> image
> So I'm not sure if it can be approved.
> @InnaAtanasova @mikerodonnell89

I think in general we need a PR that refactors from outline to border for focus

**Comment by InnaAtanasova** [comment]
Could be a Netlify preview issue but I don't see the focus in any of the examples.

**Comment by mykolavorobiov** [comment]
@stefanoScalzo I think that `box-shadow` is better than border (`box-shadow` doesn't affect the size of the element and siblings)

**Review by droshev — APPROVED** [review]
🚢 LGTM

**Pull request merged**
