### PR TITLE
docs: expound existence of max-width on drop-downs and possibility of override

### LINKED ISSUE #1295: Full width Combobox list
**Describe the bug**
When using the `fd-list--dropdown` class on a list, the options do not stretch to the entire width of the listbox popover. For example in a full-width Combobox.

> Is this issue related to a specific component?
List

> What version of the Fundamental Library Styles are you using?
0.11.0-rc.100

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
React

**Expected behavior**
List items should occupy 100% of the available width.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
[Remove max-width.](https://github.com/SAP/fundamental-styles/blob/6c012da8a0c9e58bccfb78c28b3c5e2f79fea4a7/src/_listDropdown.scss#L104)

### PR DESCRIPTION
**Pull request by prsdthkr**
## Related Issue
Closes #1295 

## Description
In this change, we
* ~remove the max-width property on the dropdown list and popover fill so that the list items and their contents can stretch to fit the popover control (Combobox input field in this case).~
* document in the examples why there is a max-width on dropdowns and the possibility of apps overriding this.
* ~update storybook to v6.0.16~
* fix Select story preview heights

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

### CODE REVIEW

**Comment by JKMarkowski** [comment]
Let's contact the responsible designer, because docs says that max-width should be included into dropdown list.
image

We also removed this limitation also on NGX, because it's hard to make it work with `popper.js`.

**Comment by jbadan** [comment]
@JKMarkowski Does this mean we should limit the input to that width? It's possible with popper to specify the max-width of the popover. Just want to be clear about how we should set it up.

**Comment by JKMarkowski** [comment]
> @JKMarkowski Does this mean we should limit the input to that width? It's possible with popper to specify the max-width of the popover. Just want to be clear about how we should set it up.
@jbadan I couldn't find anything about input on combobox/multi input. I don't like those limits(600px) on dropdown body, so I'm not against this PR, but it's against the design

**Comment by prsdthkr** [comment]
The `InputField (Fiori 3) – General Specifications` do not seem to mention any max-width for input fields. This means either this is a non-issue or the spec needs to be updated so that the dropdown body doesn't have any max-width. I will clarify with the spec author.

**Comment by InnaAtanasova** [comment]
> The `InputField (Fiori 3) – General Specifications` do not seem to mention any max-width for input fields. This means either this is a non-issue or the spec needs to be updated so that the dropdown body doesn't have any max-width. I will clarify with the spec author.

@prsdthkr , do you have any updates on this? 
The code LGTM

**Comment by prsdthkr** [comment]
> > The `InputField (Fiori 3) – General Specifications` do not seem to mention any max-width for input fields. This means either this is a non-issue or the spec needs to be updated so that the dropdown body doesn't have any max-width. I will clarify with the spec author.
> 
> @prsdthkr , do you have any updates on this?
> The code LGTM

I'm awaiting a response from the author.

**Comment by JKMarkowski** [comment]
Hi @prsdthkr, did you get any response from designers?

**Comment by prsdthkr** [comment]
> Hi @prsdthkr, did you get any response from designers?

Hey @JKMarkowski, Gerard Keane said that they don't have any problem with this. They've asked Georg Christoph for their views on this. Awaiting response. [Specification](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2051306683#Select(Fiori3)-MinandMaxWidth) remains unchanged.

**Comment by prsdthkr** [comment]
@JKMarkowski , @InnaAtanasova the specification was added to address readability issues with large dropdown popups. Currently, this specification remains unchanged; but apps have the liberty to override the max-width. I've updated the documentation for Select, Combobox Input, and Multi-Input. LMK if this is GTG.

**Review by JKMarkowski — COMMENTED** [review]
@prsdthkr Could you resolve conflicts and remove deps update from this PR? Rest LGTM

**Review by JKMarkowski — APPROVED** [review]
LGTM

**Pull request merged**
