### PR TITLE
fix: Apply fixes to Side nav's rtl

### PR DESCRIPTION
**Pull request by JKMarkowski**
## Related Issue
fixes: https://github.com/SAP/fundamental-styles/issues/873

## Description
So right now border are on left side, when RTL. Also for first level of indentation, there is padding-left and padding-right

### Before:

image

### After:
image

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
I think you forgot to push something because I can see in your screenshots the little triangle is on the other side but in the preview it doesn't change the position

Screen Shot 2020-04-20 at 5 26 08 PM

**Comment by InnaAtanasova** [comment]
Screen Shot 2020-04-20 at 5 25 45 PM

Not in the scope of this PR but the icon is not in the right position in RTL in this example

**Comment by mikerodonnell89** [comment]
> Screen Shot 2020-04-20 at 5 25 45 PM
> 
> Not in the scope of this PR but the icon is not in the right position in RTL in this example

Noticed this as well but thought i should point out that it is fine on the examples with icons (cozy and compact mode)
Screen Shot 2020-04-21 at 1 50 22 PM

**Comment by mikerodonnell89** [comment]
> I think you forgot to push something because I can see in your screenshots the little triangle is on the other side but in the preview it doesn't change the position
> 
> Screen Shot 2020-04-20 at 5 26 08 PM

Ok so after building this pr locally and copying the dist over to fundamental-ngx, the arrow is on the correct side.  However, in fundamental-styles, adding `dir="rtl"` to the parent element, I'm seeing what Inna is seeing here.

**Comment by JKMarkowski** [comment]
So I fixed RTL 
image
 now additional padding is only on condensed rtl mode
image

**Comment by JKMarkowski** [comment]
> Icon on IE 11 is not mirrored
> image

IE11 is finally supported

**Pull request merged**
