### PR TITLE
fix: section lines added according to Fiori 3 

### LINKED ISSUE #461: Product Switch broken in Firefox
1. Small screen: Missing section lines:
Screen Shot 2019-11-22 at 4 49 13 PM

In Fiori3:
Screen Shot 2019-11-22 at 4 51 10 PM

### PR DESCRIPTION
**Pull request by rengare**
## Related Issue
Closes SAP/fundamental-styles#461

## Description

- Order of css classes has been changed
-  New `border bottom` rule added for product switch item in mobile view

### Before:
69462880-32d75280-0d48-11ea-8a17-c90311e1077f

### After:
after
after rtl
after rtl active

### CODE REVIEW

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Screen Shot 2019-12-06 at 3 06 04 PM
Screen Shot 2019-12-06 at 3 06 34 PM

This is not exactly fixing the issue. When the item is selected you can clearly see the white "padding" on top, left and right. Not sure it's broken now or from another PR, but the `...` has a white background when the item is selected

**Comment by stefanoScalzo** [comment]
> Screen Shot 2019-12-06 at 3 06 04 PM
> 
> Screen Shot 2019-12-06 at 3 06 34 PM
> 
> This is not exactly fixing the issue. When the item is selected you can clearly see the white "padding" on top, left and right. Not sure it's broken now or from another PR, but the `...` has a white background when the item is selected

I agree with Inna! try and add it to the paddings instead of the margins

**Comment by rengare** [comment]
@InnaAtanasova PR was updated, I have fixed few things and resolved conflicts with master

**Comment by InnaAtanasova** [comment]
Everything is perfect (Great job fixing the issue with the little white line between the border and the background!!!!). There's a small issue on hover:
Screen Shot 2020-01-15 at 1 27 26 PM

**Comment by rengare** [comment]
> Everything is perfect (Great job fixing the issue with the little white line between the border and the background!!!!). There's a small issue on hover:
> Screen Shot 2020-01-15 at 1 27 26 PM
> 
> P.S. For some reason it doesn't show for each element. Check Strategic Procurement, Human Capital Management, Service Cloud, etc.

Fixed
product-switch-hover-fix

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
