### PR TITLE
fix: correct style in input-group 

### PR DESCRIPTION
**Pull request by OleksiyDrozdov**
## Related Issue
targets [#5938](https://github.com/SAP/fundamental-ngx/issues/5938)

## Description
Deleted not needed styles for input-group in order to avoid values changing position(padding) inside the field

## Screenshots
image
image

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [n/a] tested Storybook examples with "CSS Resources" `normalize` option 
- [n/a] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [n/a] Verified all styles in IE11
- [n/a] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [n/a] Storybook documentation has been created/updated
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Review by platon-rov — APPROVED** [review]

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
This needs to account for RTL as well, please use the new mixins for handling rtl

**Review by InnaAtanasova — APPROVED** [review]

**Review by mikerodonnell89 — APPROVED** [review]

**Comment by platon-rov** [comment]
Please check & approve changes in the Chromatic build.

**Comment by droshev** [comment]
@OleksiyDrozdov you need to check chromatic changes (UI tests task) - whether the visual changes are intended

**Comment by OleksiyDrozdov** [comment]
> @OleksiyDrozdov you need to check chromatic changes (UI tests task) - whether the visual changes are intended.
> Also by merging this PR it won't solve the issue #5938 reported in ngx.

@droshev 
could you please see gif below it will solve issue #5938 reported in ngx. Or could you please clarify what exactly is not solved.
https://user-images.githubusercontent.com/53093915/130245224-c4217b0b-ddb0-4318-8c67-236b5bd69272.mp4

**Comment by droshev** [comment]
> > @OleksiyDrozdov you need to check chromatic changes (UI tests task) - whether the visual changes are intended.
> > Also by merging this PR it won't solve the issue #5938 reported in ngx.
> 
> @droshev
> could you please see gif below it will solve issue #5938 reported in ngx. Or could you please clarify what exactly is not solved.
> https://user-images.githubusercontent.com/53093915/130245224-c4217b0b-ddb0-4318-8c67-236b5bd69272.mp4

my point is that once we merge this here, you will need to bring the version of fundamental styles in ngx in order to fix the issue. It won't happen automatically.

**Pull request merged**
