### PR TITLE
fix: Added .idea directory to gitignore

### PR DESCRIPTION
**Pull request by JKMarkowski**
## Description

I added `.idea` to gitignore, `.idea` is directory created internally by WebStorm.

### CODE REVIEW

**Comment by bcullman** [comment]
@JKMarkowski thank you for your contribution. Please sign the CLA so that we can move forward.

**Comment by JKMarkowski** [comment]
Hi, I Signed the CLA week ago on other issue, but it's still pending. I even tried to recheck it, without any effect. I don't know what is wrong with it.
image

**Comment by jbadan** [comment]
@JKMarkowski  you've definitely signed it - do you by any chance have multiple email addresses associated with your account? I seem to recall @hertweckhr1 having this problem before because of that.

Screen Shot 2019-09-03 at 2 09 57 PM

**Comment by JKMarkowski** [comment]
After rebuilding, CLA status is still pending. I'm gonna create new PR.

**Pull request closed without merging**
