### PR TITLE
feat: Adapt responsive Grid layout styles as per Fiori3

### PR DESCRIPTION
**Pull request by sKudum**
## Description
Styles as created as per Fiori3 guidelines as attached below for responsive Grid layout.

## Screenshots
1).Breakpoints are created as per below.

Screen Shot 2020-03-26 at 7 21 47 PM

2). Class and col-span calculations for label, feild and empty ratios are added as requested below.
Screen Shot 2020-03-26 at 7 24 01 PM

Note:#

 1). As discussed in the mail before, I created this even though we Grid.scss, layout-grid.scss in styles because they were not matching with Fiori standards.

2). As per Fiori docs, a Form can use many types of layouts in which Responsive Grid is one so I started with it. still we have horizontal, vertical, column layouts etc.

3). I created this layout in considering Fiori, UI5, angular material, bootstrap 4. Please do let me know if I can enhance this further.

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
This component needs to be done to work with IE11.
using grids will not work with IE11.
These grids will have to be refactored completely which is a lot more challenging then it seems. 
I have created a solution that mainly works but waiting for approval.
This PR should be closed 
@droshev @InnaAtanasova

**Comment by sKudum** [comment]
> This component needs to be done to work with IE11.
> using grids will not work with IE11.
> These grids will have to be refactored completely which is a lot more challenging then it seems.
> I have created a solution that mainly works but waiting for approval.
> This PR should be closed
> @droshev @InnaAtanasova

Hi Stefano, Could you please share the PR link, is it as per Fiori3?

**Comment by JKMarkowski** [comment]
It's great, but it's `grid` is not supported by IE11, It should be done by flexbox. @stefanoScalzo Could you link your PR here?

**Comment by sKudum** [comment]
> It's great, but the `grid` is not supported by IE11, It should be done by flexbox. @stefanoScalzo Could you link your PR here?

Hi @JKMarkowski , "-ms" prefix will help us here to resolve IE11 issue with Grid.
https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66

**Comment by stefanoScalzo** [comment]
> > It's great, but the `grid` is not supported by IE11, It should be done by flexbox. @stefanoScalzo Could you link your PR here?
> 
> Hi @JKMarkowski , "-ms" prefix will help us here to resolve IE11 issue with Grid.
> https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66

No, it doesn't still work even with the ms prefix. 
I don't have a Pr opened, The one you are seeing is for the responsiveness of our docs site. My local branch is huge and needs to have a lot of discussions and decisions are taken first. You can close your PR, don't worry about it, I'll take care of this component.

**Comment by sKudum** [comment]
> > > It's great, but the `grid` is not supported by IE11, It should be done by flexbox. @stefanoScalzo Could you link your PR here?
> > 
> > 
> > Hi @JKMarkowski , "-ms" prefix will help us here to resolve IE11 issue with Grid.
> > https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66
> 
> No, it doesn't still work even with the ms prefix despite what the article says.
> I don't have a Pr opened, The one you are seeing is for the responsiveness of our docs site. My local branch is huge and needs to have a lot of discussions and decisions are taken first. You can close your PR, don't worry about it, I'll take care of this component.

How about Flexbox? Ok, will close this PR . How about existing Grid in fundamental-styles like Grid.scss etc?

Our component signature will be like

<form
    breakPointsXL=1200px
   labelXL=4
   emptyS=2
...... etc.../>

If you share the PR it will be easy to track for us.

**Pull request closed without merging**
