### PR TITLE
feat(styles): feed list item horizon theme

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue
Relates https://github.com/SAP/fundamental-styles/issues/3354

## Description
Added delta theming for feed list item component. No breaking changes.

## Screenshots
image
image
image

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Verified all styles in IE11
- [x] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [x] Storybook documentation has been created/updated
- n/a Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Review by platon-rov — COMMENTED** [review]
* Fiori, bottom border not present for last item (it's ok in horizon):
image

Also, i see we're setting border-top for `item + item` so only between the items, but i didn't find that logic described in the wiki so probably we should just go with `border-bottom` for item every time except it's in the borderless state.

**Comment by N1XUS** [comment]
> i so probably we should just go with

I was preserving previous behaviour for the Fiori theme, where's there no bottom border for the last item

**Comment by N1XUS** [comment]
> * Fiori, bottom border not present for last item (it's ok in horizon):
> 
> image
> 
> Also, i see we're setting border-top for `item + item` so only between the items, but i didn't find that logic described in the wiki so probably we should just go with `border-bottom` for item every time except it's in the borderless state.

I was preserving previous behaviour for the Fiori theme, where's there no bottom border for the last item

**Comment by N1XUS** [comment]
@platon-rov Regarding different border widths of the track and handle:
Design specs states that track should have 0.0625rem border width, and handle should have 0.125rem

**Review by platon-rov — APPROVED** [review]

**Pull request merged**
