### PR TITLE
feat: introduce Margins and Paddings

### PR DESCRIPTION
**Pull request by kavya-b**
## Related Issue
Closes SAP/fundamental-styles#2119

## Description
This PR introduces helper modifier classes that can be added to any element that needs some spacings through paddings or margins.

### Before:
NA
### After:
Margins:
image
Paddings:
image

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [n/a] Text elements follow the truncation rules
- [n/a] hover state of the element follow design spec
- [n/a] focus state of the element follow design spec
- [n/a] active state of the element follow design spec
- [n/a] selected state of the element follow design spec
- [n/a] selected hover state of the element follow design spec
- [n/a] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [n/a] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Verified all styles in IE11
- [x] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [x] Storybook documentation has been created/updated
- [n/a] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Comment by kavya-b** [comment]
One thing I am not sure of is RTL handling. For the case of `No Margins`, if we have a margin of say 1.5rem initially, `fd-margin-end--none` will give `margin-right: 0 !important;` which is expected, but switching to RTL makes it `margin-left: 0 !important;`, but there is no way to actually retrieve the initial value of 1.5rem that the user set.
image
in RTL becomes 
image
because the `margin-right` value was already set to 0, and the original value is lost. How do we handle this?

**Comment by InnaAtanasova** [comment]
> One thing I am not sure of is RTL handling. For the case of `No Margins`, if we have a margin of say 1.5rem initially, `fd-margin-end--none` will give `margin-right: 0 !important;` which is expected, but switching to RTL makes it `margin-left: 0 !important;`, but there is no way to actually retrieve the initial value of 1.5rem that the user set.
> image
> in RTL becomes
> image
> because the `margin-right` value was already set to 0, and the original value is lost. How do we handle this?

would `margin-right: initial;` work?

**Comment by kavya-b** [comment]
> > One thing I am not sure of is RTL handling. For the case of `No Margins`, if we have a margin of say 1.5rem initially, `fd-margin-end--none` will give `margin-right: 0 !important;` which is expected, but switching to RTL makes it `margin-left: 0 !important;`, but there is no way to actually retrieve the initial value of 1.5rem that the user set.
> > image
> > in RTL becomes
> > image
> > because the `margin-right` value was already set to 0, and the original value is lost. How do we handle this?
> 
> would `margin-right: initial;` work?

I tried `initial`, `unset`, `inherit`, `revert`, `auto` with `!important` but none of them worked. Also, most of these [don't work with IE anyway.](https://caniuse.com/?search=initial)

**Comment by JKMarkowski** [comment]
Hello @kavya-b Could you try to add some mixin, which will be named `fd-not-rtl`, or `fd-ltr`? Maybe you can combine selector `::not()` with RTL. 
So for example `margin-right` will be modified only when there is not RTL, which means you won't need to reset `margin-right` on RTL

**Comment by kavya-b** [comment]
> Hello @kavya-b Could you try to add some mixin, which will be named `fd-not-rtl`, or `fd-ltr`? Maybe you can combine selector `::not()` with RTL.
> So for example `margin-right` will be modified only when there is not RTL, which means you won't need to reset `margin-right` on RTL

Hi @JKMarkowski that is a good idea and I have been trying this, but unfortunately it isn't working as expected. 
I applied `not()` in the following way:
```
&--none {
      :not([dir="rtl"]), :not([dir="rtl"]) &{
        margin-right: 0 !important;
      }

      @include fd-rtl() {
        margin-left: 0 !important;
      }
    }
```
`:not([dir="rtl"]) .fd-margin-end--none` somehow does not work as intended in RTL.
Screenshot 2021-02-12 at 2 10 10 PM

`:not([dir="rtl"] .fd-margin-end--none)` works, but is incorrect as it affects everything that is not `.fd-margin-end--none`.
Screenshot 2021-02-12 at 2 10 37 PM

Apparently, the `:not()` [does not work very well with complex selectors and has limited browser support as well.](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)

**Comment by kavya-b** [comment]
@InnaAtanasova @JKMarkowski since I was not able to get around the RTL issue for `fd-margin-begin--none` and `fd-margin-end--none` through the lib styles itself, I am now applying a workaround from the docs side, where I set the `[dir="rtl"]` for the user-specified class in `customs.scss`, while also removing `!important` from the corresponding lib modifier. [Please take a look](https://github.com/SAP/fundamental-styles/pull/2131/commits/8101a73092bd959c01d4c333d9a25aa617fd1729) if this is okay for now.

**Comment by JKMarkowski** [comment]
@kavya-b I also wasn't able to combine `at-root / rtl` with `not`. The other thing is to force users to put `[dir="ltr"]` by default, but this is something that everyone should agree on 
@InnaAtanasova What do you think about it?

**Comment by kavya-b** [comment]
> @kavya-b I also wasn't able to combine `at-root / rtl` with `not`. The other thing is to force users to put `[dir="ltr"]` by default, but this is something that everyone should agree on
> @InnaAtanasova What do you think about it?

Hi @InnaAtanasova what are your thoughts about this?

**Comment by InnaAtanasova** [comment]
> > @kavya-b I also wasn't able to combine `at-root / rtl` with `not`. The other thing is to force users to put `[dir="ltr"]` by default, but this is something that everyone should agree on
> > @InnaAtanasova What do you think about it?
> 
> Hi @InnaAtanasova what are your thoughts about this?

@kavya-b I need to discuss this with my team but from my research I found out that other libraries do not consider additional paddings and margins applied on the element. Most of the other libraries do not apply RTL at all. I will write back to you when we have some decision about it.

**Comment by InnaAtanasova** [comment]
@kavya-b we just discussed the issue and we agreed that any additional padding/margins applied on the element should be ignored.

**Comment by InnaAtanasova** [comment]
Code looks good, I am just worried the documentation is a bit confusing. 
This image is illustrating the margins:
Screen Shot 2021-02-18 at 3 41 20 PM

But usually this is the way to illustrate the paddings. The containers should all have the same size and the margins are "outside" the containers. Something like this:
Screen Shot 2021-02-18 at 3 49 50 PM

Same for paddings. This is how it's now in the documentation:
Screen Shot 2021-02-18 at 3 41 25 PM

But it's the way of illustrating margins. This is how it should be:
Screen Shot 2021-02-18 at 3 48 51 PM

I believe the best way would be to make all containers the same size and play with the backgrounds and maybe add borders to show the paddings and the margins.

**Comment by kavya-b** [comment]
> Code looks good, I am just worried the documentation is a bit confusing.
> This image is illustrating the margins:
> Screen Shot 2021-02-18 at 3 41 20 PM
> 
> But usually this is the way to illustrate the paddings. The containers should all have the same size and the margins are "outside" the containers. Something like this:
> Screen Shot 2021-02-18 at 3 49 50 PM
> 
> Same for paddings. This is how it's now in the documentation:
> Screen Shot 2021-02-18 at 3 41 25 PM
> 
> But it's the way of illustrating margins. This is how it should be:
> Screen Shot 2021-02-18 at 3 48 51 PM
> 
> I believe the best way would be to make all containers the same size and play with the backgrounds and maybe add borders to show the paddings and the margins.

@InnaAtanasova 
margins now look like this:

and paddings look like this:


hope this is okay.

**Comment by InnaAtanasova** [comment]
@kavya-b looks great! Thanks for updating the docs <3

**Review by InnaAtanasova — APPROVED** [review]

**Review by JKMarkowski — APPROVED** [review]
LGTM. Great Job!

**Pull request merged**
