### PR TITLE
fix: padding fix for compact radio button

### PR DESCRIPTION
**Pull request by DeepakSap14**
## Related Issue
Closes https://github.com/SAP/fundamental-styles/issues/1589
https://github.com/SAP/fundamental-ngx/issues/3086

## Description
Compact radio filling is not centre aligned. fixed padding for compact radio.

### Before:
Screenshot 2020-09-09 at 10 05 55 PM

### After:
Screenshot 2020-09-10 at 12 28 16 PM

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

### CODE REVIEW

**Review by droshev — DISMISSED** [review]
The focus looks off

**Comment by DeepakSap14** [comment]
> The focus looks off

fix in below PR was not taking care for compact radio.
https://github.com/SAP/fundamental-styles/pull/1283
it is fixed now.

**Review by jbadan — CHANGES_REQUESTED** [review]
The radio button aren't centered for normal or compact modes -

Screen Shot 2020-09-10 at 7 02 30 AM
Screen Shot 2020-09-10 at 7 02 39 AM

**Comment by DeepakSap14** [comment]
I have changed the content size for compact radio and cozy radio according to fiori values. but still safari compact radio is not proper, so have to do padding-top: 0.05rem.
checked in chrome, safari, firefox. now it looks much better.

Screenshot 2020-09-10 at 9 44 58 PM
Screenshot 2020-09-10 at 9 46 50 PM

Screenshot 2020-09-10 at 9 46 31 PM
Screenshot 2020-09-10 at 9 46 16 PM

**Comment by jbadan** [comment]
The compact radio buttons are still off center in the deploy preview:
Screen Shot 2020-09-10 at 12 54 59 PM

**Comment by DeepakSap14** [comment]
current implementation present in master has font-size calculated.
I am not aware how it is calculated.
My provided solution seems not to work for all browsers. i request fundamental-teams to help me in this fix.

**Comment by JKMarkowski** [comment]
Previous implementation was based on focus pseudo element, it caused some issues. Now it's outline and the `after` pseudo element is kind of free for usage. Now to indicate `checked` state there is content with some icon used, which makes it look different in other browsers/sizes.

I suggest to move `checked` indicator to `&::after` pseudo element, which will be centered inside circle. It can be built by 
```
{
   width: x;
   height: x;
   border-radius: 50%;
}
```

**Comment by DeepakSap14** [comment]
Now, have used `&:checked + .#{$block}__label::after {content: ""; position: absolute;}` and changed the values for fixing the center align issue.
checked in safari, chrome, firefox, edge browser. alignment looks good.

chrome:
Screenshot 2020-09-16 at 6 28 42 PM
Screenshot 2020-09-16 at 6 27 17 PM

safari:
Screenshot 2020-09-16 at 6 27 04 PM

**Comment by Betrozov** [comment]
plz fix Travis

**Comment by DeepakSap14** [comment]
fixing travis.

**Comment by Betrozov** [comment]
When VoiceOver is on, the outline is broken.
Screenshot 2020-09-16 at 16 39 19
But should be like this
Screenshot 2020-09-16 at 16 41 22

**Comment by DeepakSap14** [comment]
Issue related to voiceover outline can be tracked here.
https://github.com/SAP/fundamental-styles/issues/1640

In this PR, we will track fix for radio button padding of inner circle.

**Comment by DeepakSap14** [comment]
@JKMarkowski please review this.

**Review by JKMarkowski — APPROVED** [review]
LGTM, now it will be more stable

**Review by jbadan — APPROVED** [review]

**Comment by DeepakSap14** [comment]
@JKMarkowski i am not able to sign licence/cla. on hover link is not appearing.
so i am not able to merge this PR.
please merge this.

**Pull request merged**
