### PR TITLE
fix: Added .idea directory to gitignore

### PR DESCRIPTION
**Pull request by JKMarkowski**
## Description
as on previous
https://github.com/SAP/fundamental-styles/pull/310
I added .idea to gitignore, .idea is directory created internally by WebStorm.
I created new pull request, just to check if CLA works right now.

### CODE REVIEW

**Comment by jbadan** [comment]
@JKMarkowski do you have multiple email addresses attached to your account?

**Comment by JKMarkowski** [comment]
Hi @jbadan, yes, I have several.

**Comment by jbadan** [comment]
@JKMarkowski This has happened to a couple people and I wish I remember exactly what we did. I _believe_ they promoted their sap email address to primary and it started picking them up. If that doesn't work, we can reach out to the CLA team.

@hertweckhr1 I believe this happened to you with your ADA email address- do you remember what you had to do to fix it?

**Comment by hertweckhr1** [comment]
> @JKMarkowski This has happened to a couple people and I wish I remember exactly what we did. I _believe_ they promoted their sap email address to primary and it started picking them up. If that doesn't work, we can reach out to the CLA team.
> 
> @hertweckhr1 I believe this happened to you with your ADA email address- do you remember what you had to do to fix it?

@jbadan I believe I just needed to add my sap email as a verified email and I was good to go. I also added custom routing to notifications from SAP repos to go specifically to my SAP email (changed in the notifications section of profile), but not sure if that changed anything with the CLA agreement.

**Comment by jbadan** [comment]
I snuck this in here: https://github.com/SAP/fundamental-styles/pull/313

**Pull request closed without merging**
