### PR TITLE
feat(styles): add delta horizon theming for Card

### PR DESCRIPTION
**Pull request by g-cheishvili**
## Related Issue
part of #3213 

## Description
Added delta horizon variables

## BREAKING CHANGE

* Now you should add `fd-card__list` class to properly render list cards

### CODE REVIEW

**Review by platon-rov — APPROVED** [review]

**Comment by InnaAtanasova** [comment]
Please check again the variable for the border radius. This is how the Cards should look like in HC themes:
Screen Shot 2022-03-25 at 4 57 52 PM

This is how they look in fundamentals:
Screen Shot 2022-03-25 at 4 58 07 PM
Screen Shot 2022-03-25 at 4 57 59 PM

**Comment by g-cheishvili** [comment]
> Please check again the variable for the border radius. This is how the Cards should look like in HC themes: Screen Shot 2022-03-25 at 4 57 52 PM
> 
> This is how they look in fundamentals: Screen Shot 2022-03-25 at 4 58 07 PM Screen Shot 2022-03-25 at 4 57 59 PM

That's the strange thing. in pictures it looks like it has border radius, but in table, HCW and HCB border-radius is not mentioned. So I suppose It should not have border-radius. in case of the Horizon yes, it should have, but in Fiori 3 it is not mentioned

**Review by InnaAtanasova — DISMISSED** [review]

**Review by platon-rov — COMMENTED** [review]
* Fiori, Border, Table card header doesn't have border in HCW/HCB

image

* Fiori, Horizon Strange space after the table, maybe docs' issue

image

* Horizon, Table card has incorrect bottom border radius

image

* Horizon, List card has incorrect bottom border radius

image

**Review by platon-rov — COMMENTED** [review]
* Now there is no border on the header at all, but it should be present.

Screenshot 2022-04-07 at 14 52 25

* List borders issue is still relevant

image

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
