### PR TITLE
fix: bring charset at the beginning of the css files

### LINKED ISSUE #2366: @charset not at the very beginning violates CSS standard
**Describe the bug**

The [current CDN-distributed version of the `fundamental-styles.css` (0.18.0)](https://unpkg.com/fundamental-styles@0.18.0/dist/fundamental-styles.css) seems to violate the CSS standard with the `@charset` definition being preceded by the license comment.

According to the [CSS 2 Standard](https://www.w3.org/TR/CSS2/syndata.html#x57), the `@charset` definition must be placed at the very beginning of the file.

> Authors using an @charset rule must place the rule at the very beginning of the style sheet, preceded by no characters. (If a byte order mark is appropriate for the encoding used, it may precede the @charset rule.)

The [mozilla CSS docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset) states that
> [it] must be the first element in the style sheet and not be preceded by any character [...]

In our internal project that we just kicked off, we're using the fundamental-styles library and let it be processed by the frontend build tool [Vite](https://github.com/vitejs/vite) (building a Vue.js 3 application) which shows a rather longish warning about exactly this issue. Unfortunately, as a consequence, the whole content of the assembled CSS file is printed to the terminal, causing a very cluttered output.

**To Reproduce**
1. Check the content at https://unpkg.com/fundamental-styles@0.18.0/dist/fundamental-styles.css
2. See that the `@charset` rule is not at the very beginning of the file

**Expected behavior**

The `@charset` rule must not be preceded by any other character to avoid build tool warnings.

### PR DESCRIPTION
**Pull request by droshev**
## Related Issue
fixes #2366 

## Description
move `@charset` at the beginning of each css files

### CODE REVIEW

**Comment by mikerodonnell89** [comment]
This is odd, after running the build I'm seeing an empty line for the first line and still seeing this warning message

Screen Shot 2021-06-17 at 10 39 30 AM

**Comment by droshev** [comment]
how did you build?

**Comment by droshev** [comment]
how did you build?
> This is odd, after running the build I'm seeing an empty line for the first line and still seeing this warning message
> 
> 
> 
> Screen Shot 2021-06-17 at 10 39 30 AM
> 
>

**Comment by mikerodonnell89** [comment]
> how did you build?
> 
> npm run build:prod?
> 
> > This is odd, after running the build I'm seeing an empty line for the first line and still seeing this warning message
> > Screen Shot 2021-06-17 at 10 39 30 AM

seeing this with npm run build and npm run build:prod

**Comment by droshev** [comment]
> > how did you build?
> > npm run build:prod?
> > > This is odd, after running the build I'm seeing an empty line for the first line and still seeing this warning message
> > > Screen Shot 2021-06-17 at 10 39 30 AM
> 
> seeing this with npm run build and npm run build:prod

you were right. I shuffled the order and it should be fine

**Review by mikerodonnell89 — APPROVED** [review]

**Pull request merged**
