### PR TITLE
feat: refactor action bar as per the fiori 3 colors and spacing

### PR DESCRIPTION
**Pull request by manu-kr**
## Related Issue

fixes: https://github.com/SAP/fundamental-styles/issues/565

## Description

added properties and values to match Fiori 3.
documentation updated.
test scenarios simplified.

## BREAKING CHANGES:
The markup has been changed

### Before:
Screen Shot 2020-03-01 at 1 55 33 PM
Screen Shot 2020-03-01 at 1 55 56 PM
Screen Shot 2020-03-01 at 1 55 52 PM
Screen Shot 2020-03-01 at 1 55 38 PM

### After:
Screen Shot 2020-03-01 at 1 56 08 PM
Screen Shot 2020-03-01 at 1 56 38 PM
Screen Shot 2020-03-01 at 1 56 28 PM
Screen Shot 2020-03-01 at 1 56 24 PM
Screen Shot 2020-03-01 at 1 56 18 PM
Screen Shot 2020-03-01 at 1 56 13 PM

### CODE REVIEW

**Comment by manu-kr** [comment]
Hi @droshev @InnaAtanasova ,

This  PR is same as PR #635 .
https://github.com/SAP/fundamental-styles/pull/635

 I have created new PR with the finalised changes. Please approve it.

Thanks,
Manu

**Comment by droshev** [comment]
@manu-kr you marked this PR as feat then can you list all the class names that were removed and not supported anymore?

**Comment by manu-kr** [comment]
> @manu-kr you marked this PR as feat then can you list all the class names that were removed and not supported anymore?

@droshev 
I haven't removed any classes . i have just refactored existing classes and added few new modifier classes.

**Comment by manu-kr** [comment]
> ### Subtitle should also have ellipsis
> firefox
> ie11
@rengare  I am not sure which code base is you're referring, truncation already implemented. Looks like the screen shot you attached here is   wrong.
 here is right scree shot.
image

you can refer below link for the latest changes.
https://deploy-preview-701--fundamental-styles.netlify.com/components/action-bar.html

**Comment by rengare** [comment]
@manu-kr indeed sorry for that I didn't saw the link was for ngx

**Comment by InnaAtanasova** [comment]
@manu-kr could you take a look at @JKMarkowski comment and resolve the conflicts.

**Comment by manu-kr** [comment]
> image
> 
> image
> 
> Action bar with a description should have `68px` I think, you need to change `line-height` of `fd-action-bar__description` element from `1.25rem` to `1rem`

@JKMarkowski 
Fixed.

**Comment by InnaAtanasova** [comment]
Hey @manu-kr I added some updates, mostly for the documentation. Please take a look and let me know if everything looks good. Thank you

**Pull request merged**
