### PR TITLE
fix: defect tracking issues for the Form message issue

### PR DESCRIPTION
**Pull request by Lokanathan-k**
defect tracking issues for the Form message issue

## Related Issue
Closes SAP/fundamental-styles#https://github.com/SAP/fundamental-styles/issues/1593

## Description
Form message not aligned to the fiori 3 spec.
Screenshot 2020-09-10 at 10 18 34 AM

- [X] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

### CODE REVIEW

**Review by jbadan — CHANGES_REQUESTED** [review]
Please remove the code instead of commenting it out. 

Additionally, the spec has box shadow: 

Screen Shot 2020-09-10 at 6 54 43 AM
Screen Shot 2020-09-10 at 6 54 53 AM

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
+1 Jenna's comment. InputField Message has box-shadow.

**Comment by Lokanathan-k** [comment]
> +1 Jenna's comment. InputField Message has box-shadow.

I agree, And as per the spec its pointing to the right sapUiContentShadow1 

but the Visually its different when compared to fiori3 spec 

Screenshot 2020-09-10 at 8 44 34 PM

on removing the Box shadow current visual was achieved.

**Comment by salarenko** [comment]
@Lokanathan-k neither your solution is appropriate nor Fiori3 based implementation is giving expected results. I suggest closing this PR and notifying the designers about issues with the secs. There is no point of changing the existing implementation if you don't fix anything.

There is also wrong issue attached to this PR.

**Comment by Lokanathan-k** [comment]
will follow up with the issue https://github.com/SAP/fundamental-styles/issues/1599 and will be closing this issue for now

**Pull request closed without merging**
