### PR TITLE
docs: add 2 separate scrollbars for left nav and main

### PR DESCRIPTION
**Pull request by droshev**
Closes SAP/fundamental-styles#52

### CODE REVIEW

**Comment by MattL75** [comment]
Doesn't this feel weird? Mostly talking about the sticky footer.

image

There's no difference in color so it just looks like the components blend in with the footer, makes it look weird

**Comment by MattL75** [comment]
The scrollbar on the sidebar also feels weird

image

**Comment by jbadan** [comment]
@MattL75 I think the scrollbar looks weird because of the background color, we do have visible scrollbars on the other fundamental-* libraries. Maybe setting the background color on it? Although this won't work in Firefox or IE/Edge. Or we could swap the background color of the sidenav and the background for the component container so that it blends better in all systems.

**Comment by MattL75** [comment]
@jbadan Maybe we defer the scrollbar look to a later conversation? Possibly involving designers? 😅 Honestly not too sure of the best direction to go with this. It's fine for now I guess, so the remaining issue would be the white on white with the footer.

**Comment by jbadan** [comment]
@MattL75 Sounds good to me! 

I think options for the footer: not sticky or change the container backgrounds and wait for designer input.

**Comment by droshev** [comment]
I don't want to modify the colors/design more as we will have something news but I am open for tiny changes.
What do you think we should do in this ticket?

**Comment by jbadan** [comment]
@droshev Sounds good to me - can we just fix the footer issue? Have it behave like the one in fundamentals?

**Comment by droshev** [comment]
this doesn't look good:
Screen Shot 2019-06-14 at 2 52 14 PM

**Comment by MattL75** [comment]
@droshev Hard to say without live example, not even sure what you changed there.

**Comment by droshev** [comment]
- updated the header on the landing page not to be sticky
- I removed the footer when there is a left nav since it looks odd.

**Comment by droshev** [comment]
@jbadan @MattL75

**Comment by jbadan** [comment]
@droshev There's still one small problem with the expand collapse.

**Comment by droshev** [comment]
@jbadan

**Pull request merged**
