### PR TITLE
docs(styles): fix icon broken link

### PR DESCRIPTION
**Pull request by ibibhu**
Broken link in icon.stories.js :Update to https://sap.github.io/fundamental-styles/?path=/docs/introduction--overview#icons

## Related Issue
Closes SAP/fundamental-styles#

## Description
Updated the broken link in stories

## Screenshots
image

### Before:
image

### After:
image

#### Please check whether the PR fulfills the following requirements
4. Documentation
- [x] Storybook documentation has been updated

### CODE REVIEW

**Review by droshev — APPROVED** [review]

**Comment by droshev** [comment]
@ibibhu Thanks for opening the PR. Would you mind signing the CLA and updating your commit message like:
```
docs(styles): fix icon broken link
```

**Comment by ibibhu** [comment]
> @ibibhu Thanks for opening the PR. Would you mind signing the CLA and updating your commit message like:
> 
> docs(styles): fix icon broken link
> ```

**Comment by droshev** [comment]
@ibibhu do you think you can change the commit message too?

**Review by g-cheishvili — APPROVED** [review]
Nice catch, thank you!

**Review by InnaAtanasova — APPROVED** [review]

**Comment by ibibhu** [comment]
> @ibibhu do you think you can change the commit message too?

I will close this pr and a raise a new pr with the same changes with the correct commit message :)

**Comment by ibibhu** [comment]
Created a new PR :

https://github.com/SAP/fundamental-styles/pull/3784

**Pull request closed without merging**
