### PR TITLE
feat: add a new class to Button component to allow rounded buttons

### PR DESCRIPTION
**Pull request by rengare**
## Related Issue
Closes SAP/fundamental-styles#497

## Description
Round css class added for button: ```fd-button--rounded```

### Before:
Before PR a css class ```fd-image--circle``` was used

### After:
after

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
Just make sure you document the added class! LGTM

**Comment by estelaxu3** [comment]
Looks consistent across all platform.

**Comment by rengare** [comment]
added a test case for rounded button. I had some troubles with tests but I manage to fix it

**Comment by rengare** [comment]
> You shouldn't have so many updated tests in your PR. You should have only 1 test that is testing a button with rounded corners

I manage to fix this issue, now PR is clean :)

**Comment by InnaAtanasova** [comment]
We keep the PR but we need to discuss more this solution

**Comment by droshev** [comment]
@rengare do we need this PR? I think we agreed for time being not to do this in ngx as it doesn't align with Fiori 3

**Comment by rengare** [comment]
closed because it is not in a fiori 3 spec

**Pull request closed without merging**
