### PR TITLE
fix: Prevent token from growing

### PR DESCRIPTION
**Pull request by salarenko**
## Related Issue
Part of: #1760

## Description
This PR:
- removes growing behavior from Token
- add proper max-width for tokens inside the tokenizer

### Before:
image
image

### After:
image
image

### CODE REVIEW

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
I think this change is causing all the tokens to have `...` even if they don't need.

Screen Shot 2020-11-03 at 8 56 11 AM

**Comment by salarenko** [comment]
@InnaAtanasova Thanks, should be good now.
I've also updated the `max-width` of the token inside tokenizer according to Fiori3 docs.

**Review by JKMarkowski — APPROVED** [review]
Looks good for me, tested also on IE11

**Comment by salarenko** [comment]
During the review we found some different issue (not related to this PR) with controls maximum width. The issue has been described in [this ticket](https://github.com/SAP/fundamental-styles/issues/1883).

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
