### PR TITLE
fix: fixed popover misalignemnt issue with different buttons

### PR DESCRIPTION
**Pull request by JYSW380**
Closes SAP/fundamental-styles#71
fixed popover misalignment issue with different buttons. 

Before screenshot -- left side is regular button and right side is a popover
Screen Shot 2019-06-13 at 10 40 32 AM

After screenshot -- left side is regular button and right side is a popover
Screen Shot 2019-06-13 at 1 59 27 PM

### CODE REVIEW

**Comment by jbadan** [comment]
@JYSW380 Would you mind adding some before/after screenshots to the pull request?

**Comment by JYSW380** [comment]
> @JYSW380 Would you mind adding some before/after screenshots to the pull request?

Before screenshot -- left side is regular button and right side is a popover
Screen Shot 2019-06-13 at 10 40 32 AM

After screenshot -- left side is regular button and right side is a popover
Screen Shot 2019-06-13 at 1 59 27 PM

**Comment by bcullman** [comment]
buttons are still different heights. is that correct?

**Comment by JYSW380** [comment]
> buttons are still different heights. is that correct?

Before screenshot -- left side is regular button and right side is a popover
Screen Shot 2019-06-14 at 11 58 15 AM

After screenshot -- left side is regular button and right side is a popover
Screen Shot 2019-06-14 at 11 39 10 AM

**Pull request closed without merging**
