### PR TITLE
fix: update Avatar in Object Card example

### PR DESCRIPTION
**Pull request by salarenko**
## Related Issue
Part of: #1433

## Description
This PR:
- Updates Avatar component markup in Object Card example

### Before
BREAKING CHANGE:
```
<span class="fd-avatar fd-avatar--xs fd-avatar--circle sap-icon--person-placeholder" role="presentation"></span>
```

### After
BREAKING CHANGE:
```
<span class="fd-avatar fd-avatar--xs fd-avatar--circle" aria-label="Avatar">
    <i class="fd-avatar__icon sap-icon--person-placeholder" role="presentation"></i>
</span>
```

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

### CODE REVIEW

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
Missing Breaking changes in the template. Also, are you sure you don't have to update the component storyshot?

**Review by JKMarkowski — APPROVED** [review]

**Comment by salarenko** [comment]
@InnaAtanasova I've updated PR description. Running tests does not change storyshots for these changes.

**Comment by InnaAtanasova** [comment]
but I still don't see the words Breaking Change in the template...

**Comment by droshev** [comment]
> but I still don't see the words Breaking Change in the template...

I updated the wiki and also documented the Avatar's changes there

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
