### PR TITLE
fix: add fix for the Popover alignment in Avatar Group component

### PR DESCRIPTION
**Pull request by itmilos**
## Related Issue
Part of SAP/fundamental-styles#2153

## Description
Fix position for popover body 

### Before:
https://user-images.githubusercontent.com/4380815/108005485-d86a8780-6fc6-11eb-9f0a-d0d91f6d454f.png
image

### After:
image
image
image

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [ ] Includes Compact/Cosy/Tablet design
- [ ] RTL support
- [ ] tested Storybook examples with "CSS Resources" `normalize` option 
- [ ] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ ] Verified all styles in IE11
- [ ] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
@itmilos please maintain the PR template (the checkboxes)
The PR title should follow the guidelines. Should start with `fix: some text`, `feat: some text`, `docs: some text`, `chore: some text`, etc.
Did you check if this will work in fundamental-ngx? You can temporary bring the styling there and see if it's working.

**Comment by JKMarkowski** [comment]
Hi @itmilos Could you also add `[ci visual]`  to commit message - it will trigger chromatic

**Comment by mikerodonnell89** [comment]
@itmilos so the problem with this issue is not that the popover body isn't centered, in fact it is in the correct place here (right aligned).  The problem is specifically the little triangle arrow I've circled here, and how it is not centered in the middle under the circle:

108005485-d86a8780-6fc6-11eb-9f0a-d0d91f6d454f

So you should be targeting the ::before pseudoelement that is the triangle.  This is a problem with popovers throughout the whole library so I'm not sure why the linked issue only mentions it for avatar group.

Maybe a topic we can discuss in scrum, but we need to be conscious of left-to-right and right-to-left displays, so where you add some offset in LTR mode you will need to use the RTL mixin and actually subtract that offset.  We can have a call about that as it gets confusing

Also, worth mentioning that your changes here affected popovers throughout the entire library so it's always good to manually check around when manipulating commonly used components

**Review by mikerodonnell89 — CHANGES_REQUESTED** [review]
see comment above

**Pull request closed without merging**
