### PR TITLE
fix(styles,fn,deps,ci): removed third party postcss-clean and updated cssnano

### PR DESCRIPTION
**Pull request by g-cheishvili**
## Related Issue
Closes SAP/fundamental-styles#3300

## Description
This PR updates cssnano and replaces third-party library, which was wrapping clean-css library(postcss-clean) with custom sync plugin. Also replaced clean-css library's level "1" with level "2", for more aggressive removal of duplicated css properties

### CODE REVIEW

**Comment by g-cheishvili** [comment]
To reviewers: Please compare before and after outputs

**Review by platon-rov — COMMENTED** [review]
dist got bigger, is it intended? 

image

I've compared old table.css and new, you can check it here https://www.diffchecker.com/O6UiQ1Az and seems like new adds more tabulation, semicolons, leading zeros to the values (was .5rem, now 0.5rem etc), should we do that? but in new the selectors one-lined, that's okay.

**Comment by g-cheishvili** [comment]
Few bytes of difference is acceptable, but it should not be 100kb 😄 Few bytes of difference comes from `convertValues` plugin, which had bug before, it was not transforming values correctly

**Comment by g-cheishvili** [comment]
Oh, @platon-rov , versions are not same in your test. you are comparing rc29 with rc24. can you use only rc24 in both cases?

**Comment by g-cheishvili** [comment]
Now it can be checked with actual main branch. My comparisons 
Old vs New in bytes
Gzip fundamental-styles.css: 107 037 vs 106 680
Size on disk of whole dist folder: 3 182 592 vs  3 125 248

Gains are not substantial but as far as I could check works as expected

**Review by droshev — APPROVED** [review]

**Pull request merged**
