### PR TITLE
fix: popover accessibility improvements + fix popover and product switch snapshots

### PR DESCRIPTION
**Pull request by JKMarkowski**
## Related Issue
Closes https://github.com/SAP/fundamental-styles/issues/1770
Part of https://github.com/SAP/fundamental-styles/issues/1760
### Before:
image
image

### After:
image
image

#### Please check whether the PR fulfills the following requirements
4. Documentation
- [x] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Comment by prsdthkr** [comment]
Product switch in Shellbar (Right to Left) seems to be miss-styled:
image

**Comment by JKMarkowski** [comment]
Hi @prsdthkr, thanks for checking, I can't reproduce it. That's how it looks for me in RTL mode. Could you check it again?
image

**Comment by JKMarkowski** [comment]
Hi @prsdthkr , I got no clue how I can fix it, the only thing I added there is additional div element, to keep height of iframe (iFrameHeight doesn't work). And added some imports, to keep correct styling

**Comment by prsdthkr** [comment]
> Hi @prsdthkr , I got no clue how I can fix it, the only thing I added there is additional div element, to keep height of iframe (iFrameHeight doesn't work) and some imports, to bring all styles needed

@JKMarkowski seems to be unrelated to the changes. Could you create an issue for this?

**Review by prsdthkr — APPROVED** [review]
Except for Product Switch in Shellbar (Right to Left) alignment issue that should be tracked, QA LGTM.
I'm a co-author.
I made some changes in the popover stories for better accessibility and visual snapshots.
Also added avatar SVGs in storybook static assets for direct use.

**Review by salarenko — APPROVED** [review]

**Pull request merged**
