### PR TITLE
feat: Add Headers to popin mode, add fixes to selection borders

### PR DESCRIPTION
**Pull request by JKMarkowski**
## Description
Our Pop in mode wasn't prepared for thead usage on it, There was a need to have some change on styles.
I also added headers to examples.
Selected border on last row is also fixed.

### Before:
image
image
image

### After:
image
image
image

#### Please check whether the PR fulfills the following requirements

- [x] all items on the PR Review Checklist are addressed :
https://github.com/SAP/fundamental-styles/wiki/PR-Review-Checklist

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-06-08 at 2 29 36 PM
The hover splits the rows in 2

**Comment by mikerodonnell89** [comment]
@JKMarkowski I just noticed that only the top half of the rows in pop-in mode will trigger the hover background change and get a cursor: pointer.  Is this intentional?

**Comment by JKMarkowski** [comment]
@mikerodonnell89 There is just no other way to deal with hover/active states, let's have a talk about it on meeting. Cursor pointer can be on both of them.

**Comment by stefanoScalzo** [comment]
LGTM as long as we notify everyone to implement the hover states for the bottom row in implementation libraries

**Comment by droshev** [comment]
@JKMarkowski is this still blocked?

**Comment by JKMarkowski** [comment]
@droshev 
> @JKMarkowski is this still blocked?

I just had the meeting, which clarified everything. Need to add 1 small thin and it will be ready to merge.

**Pull request merged**
