### PR TITLE
feat(styles): input and shellbar delta

### PR DESCRIPTION
**Pull request by N1XUS**
## Related Issue
Closes https://github.com/SAP/fundamental-styles/issues/4410
Closes https://github.com/SAP/fundamental-styles/issues/4377
Closes https://github.com/SAP/fundamental-styles/issues/4391
Closes https://github.com/SAP/fundamental-styles/issues/4411
Closes https://github.com/SAP/fundamental-styles/issues/4393

This update introduces additional `fd-shellbar__search-field-helper` helper element to deal with borders for different interaction state of the shellbar search field

### CODE REVIEW

**Comment by InnaAtanasova** [comment]
1. ShellBar Search in normal state is missing border-bottom and box-shadow.
Design specs:
Screenshot 2023-04-18 at 2 24 09 PM



Fund-styles:
Screenshot 2023-04-18 at 2 20 51 PM

**Comment by InnaAtanasova** [comment]
2. ShellBar Search in hover state is missing border-bottom and box-shadow.
Design specs:
Screenshot 2023-04-18 at 2 23 25 PM


Fund-styles implementation:
Screenshot 2023-04-18 at 2 21 38 PM

**Comment by InnaAtanasova** [comment]
3. ShellBar Search in active state is missing border-bottom and box-shadow.
Design specs:
Screenshot 2023-04-18 at 2 23 36 PM

Fund-styles implementation:
Screenshot 2023-04-18 at 2 21 58 PM

4. The Search input is missing the clear (X) button.

**Comment by InnaAtanasova** [comment]
5. ShellBar Select in active input state is missing the dividing line between the select and the input field
Design specs:
Screenshot 2023-04-18 at 2 23 43 PM

Fund-styles implementation:
Screenshot 2023-04-18 at 2 22 44 PM

**Comment by N1XUS** [comment]
@InnaAtanasova Please re-check

**Comment by InnaAtanasova** [comment]
Screenshot 2023-04-20 at 10 00 02 AM
Screenshot 2023-04-20 at 9 59 55 AM



In my opinion the outline should have the same border radius as the element (1.125rem). It looks kinda weird to have a round button with rectangle outline.

**Comment by InnaAtanasova** [comment]
Select in compact state has a gap between the input field and the dropdown menu
Screenshot 2023-04-20 at 10 16 57 AM

**Comment by InnaAtanasova** [comment]
1. Readonly input doesn't have rounded corners
2. Disabled input shouldn't have a border bottom

Fund-styles:
Screenshot 2023-04-20 at 10 19 34 AM
Screenshot 2023-04-20 at 10 19 48 AM

Specs:

Screenshot 2023-04-20 at 10 19 57 AM

**Comment by InnaAtanasova** [comment]
Screenshot 2023-04-20 at 10 30 00 AM

will probably be fixed with the normal input fix, but there are no rounded corners.
Be careful that the disabled state has a border bottom in this case. I think I will ask the designers about this.

**Comment by N1XUS** [comment]
@InnaAtanasova Please re-check

**Review by InnaAtanasova — APPROVED** [review]

**Pull request merged**
