### PR TITLE
fix: update margin value for popover no-arrow

### PR DESCRIPTION
**Pull request by aberikashvili**
## Related Issue
Closes SAP/fundamental-styles#2690

## Description
margin value, for popover no-arrow, need to be updated, to fit combobox, multi-select, etc. dropdown popover

### Before:
image

### After:
image

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [N/A] Text elements follow the truncation rules
- [N/A] hover state of the element follow design spec
- [N/A ] focus state of the element follow design spec
- [ N/A] active state of the element follow design spec
- [ N/A] selected state of the element follow design spec
- [ N/A] selected hover state of the element follow design spec
- [ N/A] pressed state of the element follow design spec
- [ N/A] Responsiveness rules - the component has modifier classes for all breakpoints
- [ N/A] Includes Compact/Cosy/Tablet design
- [ N/A] RTL support
2. The code follows fundamental-styles code standards and style
- [ N/A] only one top level `fd-*` class is used in the file
- [ N/A] BEM naming convention is used
- [ N/A] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [ N/A] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [ N/A] `fd-reset()` mixin is applied to all elements
- [ N/A] Variables are used, if some value is used more than twice.
- [ N/A] Checked if current components can be reused, instead of having new code.
3. Testing
- [ N/A] tested Storybook examples with "CSS Resources" `normalize` option 
- [ N/A] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [ N/A] Verified all styles in IE11
- [ N/A] Updated tests
- [x] last commit message should have `[ci visual]` so it can trigger chromatic visual regression (e.g. `test: run chromatic visual regression [ci visual]`)
4. Documentation
- [ N/A] Storybook documentation has been created/updated
- [ N/A] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Comment by Smiranin** [comment]
I don't quite understand what you are fixing here, the link you shared says about problems with corners and some errors in the console in the combo-box component, in your changes I see a change in the width of the popover. Are you sure that you sent correct link on the issue?

**Comment by aberikashvili** [comment]
@Smiranin here's how combobox dropdown looks with default `margin: 0` 
image

And here's how it looks after this fix is applied:
image

**Comment by dimamarksman** [comment]
@InnaAtanasova @droshev should we create the fix here for an issue that started appearing after some changes in ngx PR that still isn't approved and merged?

**Comment by InnaAtanasova** [comment]
> @InnaAtanasova @droshev should we create the fix here for an issue that started appearing after some changes in ngx PR that still isn't approved and merged?

nope, we shouldn't. The margin should be 0. With custom margin we are applying band-aids on a bigger problem.

**Review by InnaAtanasova — CHANGES_REQUESTED** [review]
We should further investigate the problem. I really doubt we should fix the problem with custom margin.

**Pull request closed without merging**
