### PR TITLE
fix: move compact modifier class from parent to children elements

### PR DESCRIPTION
**Pull request by InnaAtanasova**
## Description 
The `compact` modifier class was applied on the wrapping div. We agreed it's better to apply it on each child element.
Also, fixed the toggle function for applying the theme in the test playground

### CODE REVIEW

**Comment by estelaxu3** [comment]
Missing the grey lines (///) in IE.

Reference from Chrome:
Screen Shot 2019-12-04 at 9 34 58 AM

**Comment by stefanoScalzo** [comment]
Looks good to me! travis keeps failing so try and push it one more time!

**Comment by InnaAtanasova** [comment]
> Missing the grey lines (///) in IE.
> 
> Reference from Chrome:
> Screen Shot 2019-12-04 at 9 34 58 AM

This is browser specific

**Comment by estelaxu3** [comment]
The rest looks great. We can release it.

**Pull request merged**
