### PR TITLE
fix: improve class structure for Switch component

### PR DESCRIPTION
**Pull request by salarenko**
## Related Issue
Closes: #1869

## Description
This PR:
- improves switch component class structure.
- removes unnecessary SCSS variables

BREAKING CHANGE:
- On `.fd-switch__label` level should be used `.fd-switch` class
- On `.fd-switch` level should be used `.fd-switch__control` class
- On `.fd-switch` level should be used `.fd-switch__control` class
- Instead of  class should be used `.fd-switch__slider`
- `.fd-switch__label` and `.fd-switch__wrapper` have been removed

### Before:
```
.fd-switch__label
    .fd-switch__text
    .fd-switch
        .fd-switch__input
        .fd-switch__wrapper
            .fd-switch__track
                .fd-switch__icon
                .fd-switch__handle
```

### After:
```
.fd-switch
    .fd-switch__text
    .fd-switch__control
        .fd-switch__input
        .fd-switch__slider
            .fd-switch__track
                .fd-switch__icon
                .fd-switch__handle
```
#### Please check whether the PR fulfills the following requirements

2. The code follows fundamental-styles code standards and style
- [x] only one top level `fd-*` class is used in the file
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Verified all styles in IE11
- [x] Updated tests
4. Documentation
- [x] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Comment by stefanoScalzo** [comment]
Screen Shot 2020-12-08 at 4 18 53 PM
Not quite sure whats going on here but its weird

**Comment by salarenko** [comment]
@stefanoScalzo I'm also not quite sure what is this comment about, its weird 😛

If this is about doubled "Off" examples, yes my mistake.

**Review by katekozlowska — APPROVED** [review]
Looks much more clear now, good job!
My minor suggestion is to keep BEM order when adding more classes, so instead of 
`class="fd-switch__icon--off fd-switch__icon sap-icon--decline"` we should use `class="fd-switch__icon fd-switch__icon--off  sap-icon--decline"`

**Comment by salarenko** [comment]
@katekozlowska Good suggestion. I've reordered the classes.

**Review by JKMarkowski — APPROVED** [review]

**Review by InnaAtanasova — APPROVED** [review]
Good job on this PR

**Pull request merged**
