### PR TITLE
fix: high contrast black side navigation nested-list/icon text shadow

### PR DESCRIPTION
**Pull request by Mike-Diaz**
## Related Issue
Closes SAP/fundamental-styles#1016

## Description
This PR focuses on a small change with the `SideNav` component. While a partial fix was implemented to add text shadow [here](https://github.com/SAP/fundamental-styles/pull/1814), some of the examples, particularly nested lists, did not receive this change which caused a failure in WCAG AAA contrast ratio minimums. Text shadow has now been added to the remaining examples which did not originally receive it.

- Side Nav Icon/Nested
   - `#FFFFFF` vs. `#0A3A5B` 11.9:1
   - `#FFFFFF` vs. `#5B3C03` 10:1

### Before:
image
image

#### Chrome:
image
image

#### IE11:
image
image

#### Please check whether the PR fulfills the following requirements

1. The output matches the design specs
- [x] All values are in `rem`
- [x] Text elements follow the truncation rules
- [x] hover state of the element follow design spec
- [x] focus state of the element follow design spec
- [x] active state of the element follow design spec
- [x] selected state of the element follow design spec
- [x] selected hover state of the element follow design spec
- [x] pressed state of the element follow design spec
- [x] Responsiveness rules - the component has modifier classes for all breakpoints
- [x] Includes Compact/Cosy/Tablet design
- [x] RTL support
2. The code follows fundamental-styles code standards and style
- [x] BEM naming convention is used
- [x] Mixins are used for repeatable code (`fd-rtl`, `fd-ellipsis`, `fd-flex`, `fd-selected`, `fd-focus`, ect.)
- [x] A11y support - keyboard support, screenreader support, proper ARIA attributes, etc.
- [x] `fd-reset()` mixin is applied to all elements
- [x] Variables are used, if some value is used more than twice.
- [x] Checked if current components can be reused, instead of having new code.
3. Testing
- [x] tested Storybook examples with "CSS Resources" `normalize` option 
- [x] tested Storybook examples with "CSS Resources" `unnormalize` option 
- [x] Verified all styles in IE11
- [x] Updated tests
4. Documentation
- [x] Storybook documentation has been created/updated
- [x] Breaking Changes [wiki](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes) has been updated in case of breaking changes.

### CODE REVIEW

**Review by jacobdevera — APPROVED** [review]
LGTM

**Comment by prsdthkr** [comment]
Hi @Mike-Diaz, change looks good. Could you sync with `master`.

**Comment by InnaAtanasova** [comment]
Hi @Mike-Diaz looks great. Why are so many tests updated? Could you sync with master as @prsdthkr suggested?

**Comment by Mike-Diaz** [comment]
@prsdthkr Thanks for checking it out! Merged!
@InnaAtanasova Thank you! Got it merged!

**Review by prsdthkr — APPROVED** [review]
QA LGTM ✅

**Pull request merged**
