### PR TITLE
docs: reduce some button examples(icon and text)

### LINKED ISSUE #881: Button - documentation page - remove button (text + icon)
Since Fiori 3 recommends only buttons with icon or with text then we should remove the examples from the doc where we show buttons with icons and text.
We should keep them as part of the playground at the same time

### PR DESCRIPTION
**Pull request by droshev**
fixes #881

### CODE REVIEW

**Comment by estelaxu3** [comment]
The documentation should be revised, there is no **Icon and Text buttons** anymore. It should only be text only or icon only. 
Screen Shot 2020-04-24 at 12 39 15 PM

**Comment by InnaAtanasova** [comment]
The title is not following the guidelines

**Comment by droshev** [comment]
> The documentation should be revised, there is no **Icon and Text buttons** anymore. It should only be text only or icon only.
> Screen Shot 2020-04-24 at 12 39 15 PM

that is correct
it is either icon or text

**Comment by estelaxu3** [comment]
> > The documentation should be revised, there is no **Icon and Text buttons** anymore. It should only be text only or icon only.
> > Screen Shot 2020-04-24 at 12 39 15 PM
> 
> that is correct
> it is either icon or text

Oh... I was ppbl having a stroke and thought Or is And. Sorry. 
Look good to me.

**Pull request merged**
